### PR TITLE
V2.0.0

### PR DESCRIPTION
**Pull request by caoxiemeihao**
**What's the changes in v2.0.0?**

1. Based on the Vite official `npm create vite` command to create the `react-ts` template
2. Based on the `vite-plugin-electron` integrated Electron

🎉 Everything looks more natural.

---

@PAXANDDOS Hey! My Bro. 👋
I reconstructed `electron-vite-react`, I think v2.0.0 will be easier to use. 😄

### CODE REVIEW

**Comment by PAXANDDOS** [comment]
Hey @caoxiemeihao! Good to see that you're still working on this project, and damn.. it changed so much after the last time I took a look, good job! 🌟
Sorry I had no time to participate before, too many things were going on, and also I found a full-time job so I'm mostly offline during the day 😵

Regarding your changes, everything seems really better, but I have some notes, I think now since I'm into commercial projects, I'm wiser in typescript and other stuff than I was before :)

In `package.json`: I remember you said that React is only used during Vite build and is not required afterward, why move it to the regular dependencies then?
You created a `public` folder at the root directory for static files, but most of them are still placed in `src/assets`
Can I create a `.editorconfig` file with your project settings? It is supported by every IDE and would make contributing easier, so people would not need to worry about their settings and you wouldn't need to fix if someone pushed with "tabs instead of spaces" 😄

Would you mind if I push a commit with those three paragraphs I mentioned above?

And you deleted the packages folder and moved its folders to the top. Honestly speaking, it looks messier to me, but I can't propose a perfect solution either 😖 It's just those `electron-*/` folders at the root directory don't look good. What about.. creating an `electron/` folder with main and preload in it? Also, we can place resources here, since they are connected to Electron only. Just proposing, that it would work out good as-is too :)
Really liked that you deleted `package-lock.json` so people can decide by themselves which package manager to use :) BTW I personally moved to pnpm, the best thing humanity created X)

I guess that's it from me, will take a better look at the evening, when my working day is over (I finish at 7 PM, it's 12 PM at the time of writing). You did a great job, and also we have almost 300 stars! I remember this project when it only hit 100 😄

**Comment by caoxiemeihao** [comment]
First of all, congratulations on finding a job 🎉. Now my country (China 🇨🇳), Programmers face a lot of layoffs; But I still have some time to maintain this project after work.

I recently worked in the [vite-plugin](https://github.com/vite-plugin), but this project is still used by many people, which is very gratifying.

Glad to hear from you, my brother. Thank you for your suggestions. 😄

**Comment by PAXANDDOS** [comment]
> First of all, congratulations on finding a job 🎉. Now my country (China 🇨🇳), Programmers face a lot of layoffs; But I still have some time to maintain this project after work.

Thanks 😄 I can not imagine the survival if I had no job, not many people here now have a stable income or any income... Sad to hear that these things are happening in your country, what's the reason for it I wonder? Hope it won't affect you tho

> I recently worked in the [vite-plugin](https://github.com/vite-plugin), but this project is still used by many people, which is very gratifying.

I noticed that :) You also used these in this project. I don't understand much about how your plugins work but they seem very efficient and they make developing easier, and it's good 😉 

Also about the changes you've just made, seems better to me 😃, still will have a better look later. Oh and we will need to update the README for new folder structure and stuff

**Comment by caoxiemeihao** [comment]
In my country(China 🇨🇳), layoffs are affected by the global economy; But I got lucky, and my income is also stable. Thank you for your concern. ❤️

The plug-in `vite-plugin-electron` is only the encapsulation of the previous `electron-vite-react/scripts/*.mjs`. It has two primary purpose: 

1. Make our project more simplified.
2. Make our project structure look more like the `react-ts` template created based on `vite create`.

**Comment by PAXANDDOS** [comment]
@caoxiemeihao Huh, I believe after your latest changes something has broke and I can't track down the issue. Try building the application and it will throw this error:
image

**Review by PAXANDDOS — CHANGES_REQUESTED** [review]
`.vscode/.debug.script.mjs` is written for the old version, which includes `scripts/` folder. Not sure what it does because I wasn't here when you implemented debug feature, so I hope you would know what to do 😅

**Comment by caoxiemeihao** [comment]
> @caoxiemeihao Huh, I believe after your latest changes something has broken and I can't track down the issue. Try building the application and it will throw this error: image
> 
> **UPD:** Or maybe it's not about your changes, I guess it can't copy the directory structure. It tries to create `dist/electron/preload` but for some reason `electron/preload` part is treated as an absolute path

The set default value of `build.outDir` may not be accurate, https://github.com/electron-vite/vite-plugin-electron/commit/134670760e8ba69fa9c231542ed28dd7879ff24d#diff-f065c431b4f45758b2e047fcd38135fdcb2327564def7a33ab41e84898210fc8R77  
Calculate `build.outDir ` is a very difficult thing 😖. If user has specified `build.outDir` in `vite.config.ts` explicitly, that will avoid this BUG 🐞

**Comment by caoxiemeihao** [comment]
Thanks very much for you review my bro. 🤗 The document will be updated in time. ⏰  
Wish you everything goes well. 🎉

**Pull request merged**
