### PR TITLE
feat: add playwright and example test

### PR DESCRIPTION
**Pull request by lifeiscontent**
# Add Playwright Support

## What I did

1. ran `npm init playwright@latest`
2. updated their example test to fit this repository

## How you can test what I did

1. install all the dependencies `npm i`
2. run `npm run build`
3. run `npm run e2e`

## What I'd like help on fixing:

1. currently its required to run `npm run build` before running tests, it'd be nice during development to be able to rely on the vite server

**notes:**

I also notice that with the vite dev server and the electron process, the two run somewhat independenly and in certain senarios either by closing the vite dev server or the electron app, one of the processes doesn't gracefully shutdown which can be a bit of an annoyance during development.

### CODE REVIEW

**Review by caoxiemeihao — APPROVED** [review]
Good job! 🎉

**Comment by caoxiemeihao** [comment]
I will try to solve the problem of automatically running `npm run build` before running test.

**Comment by caoxiemeihao** [comment]
```diff
  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build && electron-builder",
    "preview": "vite preview",
-  "e2e": "npx playwright test"
+   "pree2e": "vite build",
+   "e2e": "playwright test"
  },
```

**Comment by lifeiscontent** [comment]
@caoxiemeihao the issue with suggested pree2e is now, if I want to change something, I can't use the vite dev server to update my code, I have to continously re-run `npm run e2e` versus using something like https://www.npmjs.com/package/@deploysentinel/playwright-watch to re-run my code changes automatically during development.

**Pull request merged**
